import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import '../../src/app/globals.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
  integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
  crossorigin="anonymous"
/>;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>

      <body className={inter.className}>{children}</body>
    </html>
  );
}
