import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "../../src/app/globals.css";
import { ThemeProvider } from "../app/context/ThemeContext";
import Header from "./Header/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <ThemeProvider>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
